-- ============================================================
-- MODERN PROMETHEUS — CUSTOMER 360 DEMO
-- FILE: 01_customer_360_deployment.sql
-- PURPOSE: Production deployment SQL for ANALYTICS.CUSTOMER_360
--          Generated by Modern Prometheus DE Intelligence — Phase 6
-- ============================================================
-- BUSINESS RULES EMBEDDED:
--   BR001 — CRM is the spine. LEFT JOINs preserve all customers.
--   BR002 — Join key mapping: CUSTOMER_ID = CUST_ID = CUSTOMER_REF
--   BR003 — Order counts default to 0 for customers with no orders
--   BR004 — Satisfaction score is NULL (not 0) for no-ticket customers
--   BR005 — Open tickets defined as STATUS = 'open'
--   A001  — At-risk flag: open critical ticket OR >2 open tickets OR CSAT < 3.0
--
-- PLATFORM NOTES:
--   This file uses ANSI SQL with Snowflake defaults.
--   See platform variant comments marked with [REDSHIFT], [DATABRICKS], [DUCKDB]
-- ============================================================

USE DATABASE MP_DEMO;
USE SCHEMA ANALYTICS;

-- ── STEP 1: CREATE TARGET TABLE ───────────────────────────────
CREATE OR REPLACE TABLE ANALYTICS.CUSTOMER_360 (

    -- GROUP 1: Customer Identity (15 fields — direct copy from CRM)
    CUSTOMER_ID             VARCHAR(10)     NOT NULL    COMMENT 'Primary key. Source: CRM_CUSTOMERS.CUSTOMER_ID',
    FIRST_NAME              VARCHAR(50)                 COMMENT 'Customer first name. Source: CRM_CUSTOMERS.FIRST_NAME',
    LAST_NAME               VARCHAR(50)                 COMMENT 'Customer last name. Source: CRM_CUSTOMERS.LAST_NAME',
    EMAIL                   VARCHAR(100)                COMMENT 'Primary contact email. Source: CRM_CUSTOMERS.EMAIL',
    PHONE                   VARCHAR(30)                 COMMENT 'Phone number including country code. Source: CRM_CUSTOMERS.PHONE',
    COMPANY                 VARCHAR(100)                COMMENT 'Company name. Source: CRM_CUSTOMERS.COMPANY',
    INDUSTRY                VARCHAR(50)                 COMMENT 'Industry vertical. Source: CRM_CUSTOMERS.INDUSTRY',
    CITY                    VARCHAR(50)                 COMMENT 'City of record. Source: CRM_CUSTOMERS.CITY',
    STATE                   VARCHAR(10)                 COMMENT 'State or province code. Source: CRM_CUSTOMERS.STATE',
    COUNTRY                 VARCHAR(10)                 COMMENT 'ISO country code. Source: CRM_CUSTOMERS.COUNTRY',
    SIGNUP_DATE             DATE                        COMMENT 'Date customer first signed up. Source: CRM_CUSTOMERS.SIGNUP_DATE',
    ACCOUNT_STATUS          VARCHAR(20)                 COMMENT 'CRM account status: active / at_risk / churned. Source: CRM_CUSTOMERS.ACCOUNT_STATUS',
    ANNUAL_REVENUE_USD      NUMERIC(15,2)               COMMENT 'Customer reported annual revenue in USD. Source: CRM_CUSTOMERS.ANNUAL_REVENUE_USD',
    SALES_REP               VARCHAR(50)                 COMMENT 'Assigned sales representative. Source: CRM_CUSTOMERS.SALES_REP',
    CUSTOMER_TENURE_DAYS    INTEGER                     COMMENT 'Days since signup as of load date. Derived from SIGNUP_DATE.',

    -- GROUP 2: Order Metrics (7 fields — aggregated from ERP)
    TOTAL_ORDERS            INTEGER                     COMMENT 'Count of all orders (any status). Source: ERP_ORDERS. Default 0 for no-order customers.',
    DELIVERED_ORDERS        INTEGER                     COMMENT 'Count of delivered orders only. Source: ERP_ORDERS WHERE order_status=delivered.',
    CANCELLED_ORDERS        INTEGER                     COMMENT 'Count of cancelled orders. Source: ERP_ORDERS WHERE order_status=cancelled.',
    TOTAL_ORDER_VALUE_USD   NUMERIC(15,2)               COMMENT 'Sum of delivered order values. Excludes cancelled orders. Source: ERP_ORDERS.',
    AVG_ORDER_VALUE_USD     NUMERIC(12,2)               COMMENT 'Average delivered order value. NULL if no delivered orders.',
    FIRST_ORDER_DATE        DATE                        COMMENT 'Date of first order (any status). NULL if no orders.',
    LAST_ORDER_DATE         DATE                        COMMENT 'Date of most recent order (any status). NULL if no orders.',

    -- GROUP 3: Order Details (3 fields — most recent order via window function)
    MOST_RECENT_PRODUCT     VARCHAR(100)                COMMENT 'Product name from most recent delivered order. NULL if no delivered orders.',
    MOST_RECENT_ORDER_DATE  DATE                        COMMENT 'Order date of most recent delivered order.',
    MOST_RECENT_ORDER_VALUE NUMERIC(12,2)               COMMENT 'Total amount of most recent delivered order.',

    -- GROUP 4: Support Metrics (7 fields — aggregated from Support Tickets)
    TOTAL_TICKETS           INTEGER                     COMMENT 'Count of all support tickets. Default 0 for no-ticket customers.',
    OPEN_TICKETS            INTEGER                     COMMENT 'Count of currently open tickets (status=open). Default 0.',
    CRITICAL_TICKETS        INTEGER                     COMMENT 'Count of all critical priority tickets (any status). Default 0.',
    HAS_OPEN_CRITICAL_TICKET BOOLEAN                   COMMENT 'TRUE if any open ticket has priority=critical. Key at-risk input.',
    AVG_SATISFACTION_SCORE  NUMERIC(4,2)                COMMENT 'Average CSAT score across resolved tickets. NULL if no tickets (not zero — BR004).',
    AVG_RESOLUTION_TIME_HRS NUMERIC(8,2)               COMMENT 'Average time to resolve tickets in hours. NULL if no resolved tickets.',
    FIRST_TICKET_DATE       TIMESTAMP                   COMMENT 'Timestamp of first support ticket created. NULL if no tickets.',

    -- GROUP 5: Support Details (3 fields — most recent ticket via window function)
    MOST_RECENT_TICKET_DATE     TIMESTAMP               COMMENT 'Created_at of most recent ticket.',
    MOST_RECENT_TICKET_CATEGORY VARCHAR(30)             COMMENT 'Category of most recent ticket.',
    MOST_RECENT_TICKET_STATUS   VARCHAR(20)             COMMENT 'Current status of most recent ticket.',

    -- GROUP 6: Risk Indicators (3 fields — derived from cross-table logic — A001)
    AT_RISK_FLAG            BOOLEAN                     COMMENT 'BUSINESS RULE A001: TRUE if open critical ticket OR open_tickets>2 OR avg_satisfaction<3.0',
    RISK_REASON             VARCHAR(200)                COMMENT 'Human-readable explanation of why at_risk_flag is TRUE. NULL if not at risk.',
    LOW_SATISFACTION_FLAG   BOOLEAN                     COMMENT 'TRUE if avg_satisfaction_score < 3.0. Sub-component of at_risk_flag.',

    -- Audit
    LOADED_AT               TIMESTAMP DEFAULT CURRENT_TIMESTAMP()   COMMENT 'Timestamp when this row was loaded into the Customer 360 table.'
);

-- ── STEP 2: INSERT — CTE-BASED TRANSFORMATION ─────────────────
-- One CTE per field group for readability and testability.
-- Each CTE is independently auditable.

INSERT INTO ANALYTICS.CUSTOMER_360 (
    CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, COMPANY, INDUSTRY,
    CITY, STATE, COUNTRY, SIGNUP_DATE, ACCOUNT_STATUS, ANNUAL_REVENUE_USD,
    SALES_REP, CUSTOMER_TENURE_DAYS,
    TOTAL_ORDERS, DELIVERED_ORDERS, CANCELLED_ORDERS, TOTAL_ORDER_VALUE_USD,
    AVG_ORDER_VALUE_USD, FIRST_ORDER_DATE, LAST_ORDER_DATE,
    MOST_RECENT_PRODUCT, MOST_RECENT_ORDER_DATE, MOST_RECENT_ORDER_VALUE,
    TOTAL_TICKETS, OPEN_TICKETS, CRITICAL_TICKETS, HAS_OPEN_CRITICAL_TICKET,
    AVG_SATISFACTION_SCORE, AVG_RESOLUTION_TIME_HRS, FIRST_TICKET_DATE,
    MOST_RECENT_TICKET_DATE, MOST_RECENT_TICKET_CATEGORY, MOST_RECENT_TICKET_STATUS,
    AT_RISK_FLAG, RISK_REASON, LOW_SATISFACTION_FLAG
)

WITH

-- ── CTE 1: Customer Base (spine) ──────────────────────────────
-- BR001: CRM is the spine. Every customer appears in the output.
customer_base AS (
    SELECT
        customer_id,
        first_name,
        last_name,
        email,
        phone,
        company,
        industry,
        city,
        state,
        country,
        signup_date,
        account_status,
        annual_revenue_usd,
        sales_rep,
        -- Snowflake: DATEDIFF('day', signup_date, CURRENT_DATE())
        -- Redshift:  DATEDIFF('day', signup_date, CURRENT_DATE)
        -- Databricks: DATEDIFF(CURRENT_DATE(), signup_date)
        -- DuckDB:    DATE_DIFF('day', signup_date, CURRENT_DATE)
        DATEDIFF('day', signup_date, CURRENT_DATE()) AS customer_tenure_days
    FROM RAW_DATA.CRM_CUSTOMERS
),

-- ── CTE 2: Order Metrics (aggregated per customer) ────────────
-- BR002: Join on CUST_ID = CUSTOMER_ID (different names, same values)
-- BR003: COALESCE to 0 for count fields — no-order customers show 0, not NULL
order_metrics AS (
    SELECT
        cust_id AS customer_id,  -- BR002: CUST_ID maps to CUSTOMER_ID
        COUNT(order_id)                                                     AS total_orders,
        COUNT(CASE WHEN order_status = 'delivered' THEN 1 END)              AS delivered_orders,
        COUNT(CASE WHEN order_status = 'cancelled' THEN 1 END)              AS cancelled_orders,
        SUM(CASE WHEN order_status = 'delivered' THEN total_amount_usd
                 ELSE 0 END)                                                AS total_order_value_usd,
        AVG(CASE WHEN order_status = 'delivered' THEN total_amount_usd END) AS avg_order_value_usd,
        MIN(order_date)                                                     AS first_order_date,
        MAX(order_date)                                                     AS last_order_date
    FROM RAW_DATA.ERP_ORDERS
    GROUP BY cust_id
),

-- ── CTE 3: Order Details (most recent delivered order) ─────────
-- Window function to get the single most recent delivered order per customer.
-- Snowflake: QUALIFY ROW_NUMBER() OVER (...)= 1
-- Redshift/Databricks/DuckDB: wrap in subquery with WHERE rn = 1
order_details AS (
    SELECT
        cust_id AS customer_id,
        product_name  AS most_recent_product,
        order_date    AS most_recent_order_date,
        total_amount_usd AS most_recent_order_value
    FROM (
        SELECT
            cust_id,
            product_name,
            order_date,
            total_amount_usd,
            ROW_NUMBER() OVER (
                PARTITION BY cust_id
                ORDER BY order_date DESC
            ) AS rn
        FROM RAW_DATA.ERP_ORDERS
        WHERE order_status = 'delivered'
    ) ranked
    WHERE rn = 1
),

-- ── CTE 4: Support Metrics (aggregated per customer) ──────────
-- BR002: Join on CUSTOMER_REF = CUSTOMER_ID
-- BR004: AVG(satisfaction_score) returns NULL if no tickets — intentional
-- BR005: Open tickets = STATUS = 'open'
support_metrics AS (
    SELECT
        customer_ref AS customer_id,  -- BR002: CUSTOMER_REF maps to CUSTOMER_ID
        COUNT(ticket_id)                                                        AS total_tickets,
        COUNT(CASE WHEN status = 'open' THEN 1 END)                             AS open_tickets,
        COUNT(CASE WHEN priority = 'critical' THEN 1 END)                       AS critical_tickets,
        -- HAS_OPEN_CRITICAL: TRUE if any open ticket is critical priority
        CASE WHEN COUNT(CASE WHEN status = 'open'
                             AND priority = 'critical' THEN 1 END) > 0
             THEN TRUE ELSE FALSE END                                            AS has_open_critical_ticket,
        AVG(satisfaction_score)                                                  AS avg_satisfaction_score,  -- BR004: NULL if no tickets
        AVG(resolution_time_hrs)                                                 AS avg_resolution_time_hrs,
        MIN(created_at)                                                          AS first_ticket_date
    FROM RAW_DATA.SUPPORT_TICKETS
    GROUP BY customer_ref
),

-- ── CTE 5: Support Details (most recent ticket) ───────────────
support_details AS (
    SELECT
        customer_ref AS customer_id,
        created_at    AS most_recent_ticket_date,
        category      AS most_recent_ticket_category,
        status        AS most_recent_ticket_status
    FROM (
        SELECT
            customer_ref,
            created_at,
            category,
            status,
            ROW_NUMBER() OVER (
                PARTITION BY customer_ref
                ORDER BY created_at DESC
            ) AS rn
        FROM RAW_DATA.SUPPORT_TICKETS
    ) ranked
    WHERE rn = 1
),

-- ── CTE 6: Risk Indicators (A001 — approved at-risk logic) ────
-- A001: at_risk_flag = TRUE when ANY of:
--   (1) has_open_critical_ticket = TRUE
--   (2) open_tickets > 2
--   (3) avg_satisfaction_score < 3.0
-- RISK_REASON: human-readable explanation for whoever reads this table
risk_indicators AS (
    SELECT
        customer_id,
        CASE
            WHEN has_open_critical_ticket = TRUE THEN TRUE
            WHEN open_tickets > 2               THEN TRUE
            WHEN avg_satisfaction_score < 3.0   THEN TRUE
            ELSE FALSE
        END AS at_risk_flag,
        CASE
            WHEN has_open_critical_ticket = TRUE
                THEN 'Open critical support ticket requires immediate resolution'
            WHEN open_tickets > 2
                THEN 'High volume of open tickets (' || open_tickets || ' open)'
            WHEN avg_satisfaction_score < 3.0
                THEN 'Low satisfaction score (' || ROUND(avg_satisfaction_score, 1) || '/5.0)'
            ELSE NULL
        END AS risk_reason,
        CASE WHEN avg_satisfaction_score < 3.0 THEN TRUE ELSE FALSE END AS low_satisfaction_flag
    FROM support_metrics
)

-- ── FINAL SELECT: Join all CTEs on customer spine ─────────────
SELECT
    cb.customer_id,
    cb.first_name,
    cb.last_name,
    cb.email,
    cb.phone,
    cb.company,
    cb.industry,
    cb.city,
    cb.state,
    cb.country,
    cb.signup_date,
    cb.account_status,
    cb.annual_revenue_usd,
    cb.sales_rep,
    cb.customer_tenure_days,

    COALESCE(om.total_orders, 0)            AS total_orders,        -- BR003
    COALESCE(om.delivered_orders, 0)        AS delivered_orders,
    COALESCE(om.cancelled_orders, 0)        AS cancelled_orders,
    COALESCE(om.total_order_value_usd, 0)   AS total_order_value_usd,
    om.avg_order_value_usd,
    om.first_order_date,
    om.last_order_date,

    od.most_recent_product,
    od.most_recent_order_date,
    od.most_recent_order_value,

    COALESCE(sm.total_tickets, 0)           AS total_tickets,       -- BR003
    COALESCE(sm.open_tickets, 0)            AS open_tickets,
    COALESCE(sm.critical_tickets, 0)        AS critical_tickets,
    COALESCE(sm.has_open_critical_ticket, FALSE) AS has_open_critical_ticket,
    sm.avg_satisfaction_score,              -- BR004: NULL intentional for no-ticket customers
    sm.avg_resolution_time_hrs,
    sm.first_ticket_date,

    sd.most_recent_ticket_date,
    sd.most_recent_ticket_category,
    sd.most_recent_ticket_status,

    COALESCE(ri.at_risk_flag, FALSE)        AS at_risk_flag,        -- FALSE if no ticket history
    ri.risk_reason,
    COALESCE(ri.low_satisfaction_flag, FALSE) AS low_satisfaction_flag

FROM customer_base cb
LEFT JOIN order_metrics  om ON cb.customer_id = om.customer_id   -- BR001, BR002
LEFT JOIN order_details  od ON cb.customer_id = od.customer_id   -- BR001
LEFT JOIN support_metrics sm ON cb.customer_id = sm.customer_id  -- BR001, BR002
LEFT JOIN support_details sd ON cb.customer_id = sd.customer_id  -- BR001
LEFT JOIN risk_indicators ri ON cb.customer_id = ri.customer_id  -- A001
;

-- ── STEP 3: VALIDATION QUERIES ────────────────────────────────

-- V1: Row count (expect 15)
SELECT COUNT(*) AS total_customers FROM ANALYTICS.CUSTOMER_360;

-- V2: At-risk customers (expect 2)
SELECT
    customer_id,
    first_name || ' ' || last_name AS customer_name,
    company,
    industry,
    total_order_value_usd,
    avg_satisfaction_score,
    at_risk_flag,
    risk_reason
FROM ANALYTICS.CUSTOMER_360
WHERE at_risk_flag = TRUE
ORDER BY total_order_value_usd DESC;

-- V3: Full portfolio view
SELECT
    customer_id,
    company,
    account_status,
    total_orders,
    total_order_value_usd,
    total_tickets,
    open_tickets,
    avg_satisfaction_score,
    at_risk_flag
FROM ANALYTICS.CUSTOMER_360
ORDER BY total_order_value_usd DESC NULLS LAST;

-- V4: Portfolio summary (executive view)
SELECT
    COUNT(*)                                            AS total_customers,
    SUM(total_order_value_usd)                          AS portfolio_value_usd,
    ROUND(AVG(total_order_value_usd), 0)                AS avg_customer_value_usd,
    SUM(CASE WHEN at_risk_flag THEN 1 ELSE 0 END)       AS at_risk_customers,
    SUM(CASE WHEN at_risk_flag THEN total_order_value_usd ELSE 0 END) AS at_risk_value_usd,
    ROUND(
        100.0 * SUM(CASE WHEN at_risk_flag THEN total_order_value_usd ELSE 0 END)
        / NULLIF(SUM(total_order_value_usd), 0)
    , 1)                                                AS at_risk_value_pct
FROM ANALYTICS.CUSTOMER_360;

-- V5: Industry breakdown
SELECT
    industry,
    COUNT(*)                                            AS customers,
    SUM(total_order_value_usd)                          AS industry_value_usd,
    SUM(CASE WHEN at_risk_flag THEN 1 ELSE 0 END)       AS at_risk_count,
    ROUND(AVG(avg_satisfaction_score), 2)               AS avg_satisfaction
FROM ANALYTICS.CUSTOMER_360
GROUP BY industry
ORDER BY industry_value_usd DESC NULLS LAST;

-- ── EXPECTED RESULTS ──────────────────────────────────────────
-- V1: 15 rows
-- V2: C013 BankWest ($457,650) — open critical ticket
--     C012 ManufaCT ($22,800)  — low satisfaction (2.0)
-- V4: portfolio $1,989,950 | at-risk $480,450 (24.1%)
